### ISSUE TITLE
Use Artifacts for Tesseract OCR

### ISSUE THREAD

**Issue by Nosferican** [leferrad/OCReract.jl#6]
It seems installing the OCReract.jl doesn't install Tesseract OCR. It should work by using Tesseract OCR as an artifact.

**Comment by leferrad** [comment]
That's right, it assumes you already have installed Tesseract and the command `tesseract` works. You can see here that check: https://github.com/leferrad/OCReract.jl/blob/master/src/tesseract.jl#L14-L23

I can make that clear in the documentation, since this is only a wrapper. However, could you tell me about your idea of handling it as an artifact? Which changes you propose? Thanks!

**Comment by Nosferican** [comment]
The idea is to use Tesseract_jll (https://github.com/JuliaPackaging/Yggdrasil/tree/master/T/Tesseract) which uses Julia to provide the binaries (by installing OCReract.jl you get a statically linked Tesseract distribution to use). For example, rather than installing and running ImageMagick from the CLI, I can use the `ImageMagick_jll` like
```
using ImageMagick_jll: imagemagick_convert
imagemagick_convert() do exe_path
    run(`$exe_path -density 300 "$infile[0]" "$outfile"`)
end
```
CC: @pixel27 (how does one add languages to the jll package?)

**Comment by leferrad** [comment]
Sorry for the late reply. It sounds very useful, but I still don't get the whole idea: if the change is just to get a link to Tesseract binary to execute in the code, and not to add a big dependency just to have the binary available (which could be installed without problems by the user, with proper documentation to do that if needed), then it should be fine. 
Could you do a PR with your proposal? Then we can review the convenience of Tesseract installed by the user vs Tesseract artifact handled by this library.
Thanks again for this contribution!

**Comment by leferrad** [comment]
Closing this until a specific proposal is defined
